name: GitHub Actions
on: [push]
jobs:
  Code-Style:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Python Code Quality and Lint
        uses: ricardochaves/python-lint@v1.3.0
        with:
          python-root-list: "**/day*.py"
          use-black: false
          use-mypy: false
          extra-pycodestyle-options: "--max-line-length=120"
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Pytest
        uses: fylein/python-pytest-github-action@v2