name: GitHub Actions
on: [push]
jobs:
  Code-Style:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Python Code Quality and Lint
        uses: ricardochaves/python-lint@v1.3.0
        with:
          python-root-list: "**/day*.py"
          use-black: false
          extra-pycodestyle-options: "--max-line-length=120"
